package com.henu.henuxin.mapper;

import com.henu.henuxin.model.MyFriends;
import com.henu.henuxin.model.MyFriendsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MyFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    long countByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    int deleteByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    int insert(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    int insertSelective(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    List<MyFriends> selectByExampleWithRowbounds(MyFriendsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    List<MyFriends> selectByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    MyFriends selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") MyFriends record, @Param("example") MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    int updateByExample(@Param("record") MyFriends record, @Param("example") MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    int updateByPrimaryKeySelective(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Sep 28 18:26:00 CST 2019
     */
    int updateByPrimaryKey(MyFriends record);
}