package com.henu.henuxin.model;

public class MyFriends {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friends.id
     *
     * @mbg.generated Sun Oct 06 11:45:43 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friends.my_user_id
     *
     * @mbg.generated Sun Oct 06 11:45:43 CST 2019
     */
    private String myUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friends.my_friends_user_id
     *
     * @mbg.generated Sun Oct 06 11:45:43 CST 2019
     */
    private String myFriendsUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friends.id
     *
     * @return the value of my_friends.id
     *
     * @mbg.generated Sun Oct 06 11:45:43 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friends.id
     *
     * @param id the value for my_friends.id
     *
     * @mbg.generated Sun Oct 06 11:45:43 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friends.my_user_id
     *
     * @return the value of my_friends.my_user_id
     *
     * @mbg.generated Sun Oct 06 11:45:43 CST 2019
     */
    public String getMyUserId() {
        return myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friends.my_user_id
     *
     * @param myUserId the value for my_friends.my_user_id
     *
     * @mbg.generated Sun Oct 06 11:45:43 CST 2019
     */
    public void setMyUserId(String myUserId) {
        this.myUserId = myUserId == null ? null : myUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friends.my_friends_user_id
     *
     * @return the value of my_friends.my_friends_user_id
     *
     * @mbg.generated Sun Oct 06 11:45:43 CST 2019
     */
    public String getMyFriendsUserId() {
        return myFriendsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friends.my_friends_user_id
     *
     * @param myFriendsUserId the value for my_friends.my_friends_user_id
     *
     * @mbg.generated Sun Oct 06 11:45:43 CST 2019
     */
    public void setMyFriendsUserId(String myFriendsUserId) {
        this.myFriendsUserId = myFriendsUserId == null ? null : myFriendsUserId.trim();
    }
}