server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://106.75.109.78:3306/henuxin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1003Lv@@
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.henu.henuxin.model
  mapper-locations: classpath:mapper/*.xml
####阿里oss
endpoint: http://oss-cn-beijing.aliyuncs.com
accessKeyId: LTAIlAHWpVWuoRQH
accessKeySecret: Zg6oKK5WFdMiN8IEmKPAUWAvGUxfzG
bucketName: shuixin
