server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/henuxin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: *****
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.henu.henuxin.model
  mapper-locations: classpath:mapper/*.xml
####阿里oss
endpoint: *******
accessKeyId: 
accessKeySecret: 
bucketName: 
